/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/radicon.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sun_1.geometry}
        material={materials.Mat}
        position={[0.1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude8_1.geometry}
        material={materials.Mat}
        position={[0, -6.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude7_1.geometry}
        material={materials.Mat}
        position={[4.9, -4.8, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude6_1.geometry}
        material={materials.Mat}
        position={[-4.9, -4.9, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude5_1.geometry}
        material={materials.Mat}
        position={[6.3, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude4_1.geometry}
        material={materials.Mat}
        position={[-6.3, -0.1, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude3_1.geometry}
        material={materials.Mat}
        position={[0.1, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude2_1.geometry}
        material={materials.Mat}
        position={[5, 5, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude1_1.geometry}
        material={materials.Mat}
        position={[-4.9, 4.9, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude_1.geometry}
        material={materials.Mat}
        position={[0.1, 6.2, 0]}
      />
    </group>
  )
}

useGLTF.preload('/radishsun.gltf')
